# Generated by Django 4.1.1 on 2024-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Ready')], default='', max_length=1),
        ),
    ]
